### ISSUE TITLE
Unable to set up project for development

### ISSUE THREAD

**Issue by braj-ankit** [mapbox/mapboxgl-powerbi#373]
Hi I am working with `Node v12.16.1`, and trying to setup a working copy of this on my dev system (Windows 10)

#### Steps on what I have done:

- cloned a local copy of this project.
- fire up `npm install`.
- add a `.api/v2.1.0` to project root to resolve `IVisual` compilation issues.
- installed `powerbi-visuals-tools` version 2.5.0
- fire up pbiviz start 

I had set Power BI project [using this documentation here](https://docs.microsoft.com/en-us/power-bi/developer/visuals/custom-visual-develop-tutorial)

when I  run the project and drag drop the developer visual widget from visualization it fails to initialize the widget and throws the below error in the developer console.
 
```
Uncaught TypeError: supercluster is not a function
    at Cluster.createCluster (<anonymous>:10467:32)
    at new Cluster (<anonymous>:10418:45)
    at <anonymous>:10653:30
    at <anonymous>:10656:15
    at <anonymous>:10657:11
    at <anonymous>:10658:7
    at Object.<anonymous> (<anonymous>:10659:3)
    at Object.<anonymous> (<anonymous>:13379:30)
    at __webpack_require__ (<anonymous>:35:30)
    at <anonymous>:99:18
 ```

**Comment by ImCarrot** [comment]
@BrajAnkit1996 Please attach your `package.json` & `pbiviz.json` for reference

**Comment by BrajAnkit1996** [comment]
### pbiviz.json

```
{
  "visual": {
    "name": "mapboxGLMap",
    "displayName": "Mapbox Visual",
    "guid": "PBI_CV_EB3A4088_75C5_4746_9D8B_255A7B7ECD6C",
    "visualClassName": "MapboxMap",
    "version": "1.5.0",
    "description": "Visualize massive location data with custom map styles, using circle, heatmap, choropleth, and cluster layers.",
    "supportUrl": "www.mapbox.com/help",
    "gitHubUrl": "https://github.com/mapbox/mapboxgl-powerbi"
  },
  "apiVersion": "2.1.0",
  "author": {
    "name": "Mapbox",
    "email": "ryan.baumann@mapbox.com"
  },
  "assets": {
    "icon": "assets/icon.png"
  },
  "externalJS": [
    "node_modules/mapbox-gl/dist/mapbox-gl.js",
    "node_modules/@mapbox/mapbox-gl-draw/dist/mapbox-gl-draw.js",
    "node_modules/supercluster/dist/supercluster.min.js",
    "node_modules/@mapbox/mapbox-gl-geocoder/dist/mapbox-gl-geocoder.min.js",
    "src/js/turf-bundle-min.js",
    "node_modules/chroma-js/chroma.min.js",
    "src/js/fast-deep-equal.min.js",
    "node_modules/globalize/lib/globalize.js",
    "node_modules/globalize/lib/cultures/globalize.culture.en-US.js",
    "node_modules/powerbi-visuals-utils-typeutils/lib/index.js",
    "node_modules/powerbi-visuals-utils-dataviewutils/lib/index.js",
    "node_modules/powerbi-visuals-utils-formattingutils/lib/index.js",
    "src/js/mdn-array-find.js",
    "src/js/mapboxglAdaptor.js"
  ],
  "style": "style/visual.less",
  "capabilities": "capabilities.json",
  "stringResources": []
}
```

### package.json

```
{
  "name": "mapboxgl-powerbi",
  "version": "1.5.0",
  "description": "Mapbox Visual for Power BI",
  "main": "index.js",
  "scripts": {
    "pbi": "pbiviz",
    "pbicerti": "pbiviz --install-cert",
    "package": "pbiviz package",
    "pretest": "pbiviz package --resources --no-minify --no-pbiviz --no-plugin",
    "test": "karma start",
    "start": "pbiviz start",
    "turf-build": "browserify ./src/build/turf-build.js -s turf --debug --plugin [minifyify --output src/js/turf-bundle.js] > src/js/turf-bundle-min.js"
  },
  "author": "Ryan Baumann",
  "license": "MIT",
  "dependencies": {
    "@mapbox/mapbox-gl-draw": "^1.1.2",
    "@mapbox/mapbox-gl-geocoder": "^4.4.2",
    "@turf/bbox": "^6.0.1",
    "@turf/bbox-polygon": "^6.0.1",
    "@turf/boolean-contains": "^6.0.1",
    "@turf/boolean-overlap": "^6.0.1",
    "@turf/center": "^6.0.1",
    "@turf/helpers": "^6.1.4",
    "@turf/meta": "^6.0.2",
    "@turf/simplify": "^5.1.5",
    "@types/geojson": "^1.0.6",
    "@types/mapbox-gl": "^0.51.4",
    "chroma-js": "^1.3.5",
    "mapbox-gl": "^1.0.0",
    "powerbi-client": "^2.6.7",
    "powerbi-visuals-api": "^2.6.2",
    "powerbi-visuals-tools": "^2.5.0",
    "powerbi-visuals-utils-dataviewutils": "^1.5.0",
    "powerbi-visuals-utils-formattingutils": "^3.1.0",
    "powerbi-visuals-utils-testutils": "^1.3.2",
    "powerbi-visuals-utils-typeutils": "^1.2.0",
    "supercluster": "^4.1.1",
    "typed-rest-client": "^1.0.11"
  },
  "devDependencies": {
    "jasmine-core": "^2.8.0",
    "karma": "^2.0.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-coverage": "^1.1.1",
    "karma-jasmine": "^1.1.1",
    "karma-remap-istanbul": "^0.6.0",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-typescript-preprocessor": "^0.3.1",
    "minifyify": "^7.3.5"
  }
}
```

**Comment by arvapalliramu** [comment]
I am getting the same error, is issue is resolved for you?
